/**
 * ─────────────────────────────────────────────────────────────────
 *  MAZAJ LOGO GEOMETRY — the algorithmic heart of the brand mark
 * ─────────────────────────────────────────────────────────────────
 *  Pure, deterministic geometry shared by:
 *    • src/components/hookah/logo.tsx  (the animated in-app logo)
 *    • scripts/render-logo-icons.ts    (the rasterized PWA icons)
 *
 *  The smoke tendrils are NOT hand-drawn: each is generated by a
 *  seeded PRNG driving a sine-perturbed bezier chain, so the smoke
 *  looks organic yet renders identically on server & client (no
 *  hydration drift) and in the offline icon rasterizer.
 *
 *  Coordinate space: viewBox 0 0 120 132 (hookah below, smoke above).
 * ─────────────────────────────────────────────────────────────────
 */

/** Deterministic PRNG (mulberry32) — same sequence for a given seed. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export const LOGO_VIEWBOX = { w: 120, h: 132 } as const;

/* ── The hookah — elegant single-line line-art ────────────────────── */

/** The vase bulb (open at the neck so the stem visually continues it). */
export const PATH_VASE =
  "M 46 92 C 38 96 34 104 39 112 C 44 119 76 119 81 112 C 86 104 82 96 74 92";

/** Subtle engraving / water line inside the vase. */
export const PATH_VASE_LINE = "M 45 104 C 53 108.5 67 108.5 75 104";

/** The center stem. */
export const PATH_STEM = "M 60 92 L 60 62";

/** The tray (shallow saucer under the bowl). */
export const PATH_TRAY = "M 40 67 Q 60 58 80 67";

/** The bowl (trapezoid cup sitting on the tray). */
export const PATH_BOWL = "M 51 44 L 48 58 C 48 62 72 62 72 58 L 69 44";

/** The bowl rim lip. */
export const PATH_BOWL_RIM = "M 51 44 Q 60 40.5 69 44";

/** The hose — springs from the stem and curls. */
export const PATH_HOSE =
  "M 63 84 C 75 84 83 90 90 86 C 96 82 96 74 89 73";

/** Ember (coal) positions on the bowl rim. */
export const COALS: { x: number; y: number; r: number }[] = [
  { x: 55, y: 38.5, r: 2.1 },
  { x: 60.5, y: 36.8, r: 2.4 },
  { x: 66, y: 38.8, r: 2.1 },
];

/** Draw-on order for the entrance animation. */
export const HOOKAH_STROKES: {
  d: string;
  /** framer-motion pathLength delay (seconds) */
  delay: number;
  /** stroke width */
  width: number;
}[] = [
  { d: PATH_VASE, delay: 0, width: 3.4 },
  { d: PATH_STEM, delay: 0.45, width: 3.4 },
  { d: PATH_TRAY, delay: 0.6, width: 3.2 },
  { d: PATH_BOWL, delay: 0.75, width: 3.2 },
  { d: PATH_BOWL_RIM, delay: 1.0, width: 2.6 },
  { d: PATH_VASE_LINE, delay: 1.05, width: 2.2 },
  { d: PATH_HOSE, delay: 1.15, width: 3.0 },
];

/* ── The smoke — procedurally generated tendrils ──────────────────── */

export interface TendrilSpec {
  seed: number;
  x0: number;
  y0: number;
  rise: number;
  segments: number;
  sway: number;
  width: number;
  opacity: number;
  /** seconds for the upward dash drift loop */
  drift: number;
}

/** The three living smoke curls (fixed seeds → deterministic). */
export const SMOKE_TENDRILS: TendrilSpec[] = [
  { seed: 11, x0: 54.5, y0: 41, rise: 33, segments: 5, sway: 6.5, width: 2.6, opacity: 0.5, drift: 11 },
  { seed: 47, x0: 60.5, y0: 39, rise: 36, segments: 6, sway: 8.0, width: 3.3, opacity: 0.62, drift: 14 },
  { seed: 83, x0: 66, y0: 41, rise: 31, segments: 5, sway: 6.0, width: 2.3, opacity: 0.44, drift: 9 },
];

/**
 * Generate one smoke tendril: a chain of cubic beziers whose horizontal
 * sway follows a sine wave (amplitude grows with height) with a touch of
 * seeded jitter — smoke that feels alive but is fully deterministic.
 */
export function smokePath(spec: TendrilSpec): string {
  const rnd = mulberry32(spec.seed);
  const stepY = spec.rise / spec.segments;
  const phase = rnd() * Math.PI * 2;
  const freq = 1.7 + rnd() * 0.9;
  let x = spec.x0;
  let y = spec.y0;
  let d = `M ${x.toFixed(1)} ${y.toFixed(1)}`;
  for (let i = 0; i < spec.segments; i++) {
    const t = (i + 1) / spec.segments;
    const amp = spec.sway * (0.28 + t * 0.85);
    const dx = Math.sin(phase + t * Math.PI * freq) * amp + (rnd() - 0.5) * 2.4;
    const dy = -stepY * (0.85 + rnd() * 0.3);
    const nx = x + dx;
    const ny = y + dy;
    const cx1 = x + dx * 0.25 + (rnd() - 0.5) * 1.6;
    const cy1 = y + dy * 0.42;
    const cx2 = nx - dx * 0.25 + (rnd() - 0.5) * 1.6;
    const cy2 = ny - dy * 0.35;
    d += ` C ${cx1.toFixed(1)} ${cy1.toFixed(1)} ${cx2.toFixed(1)} ${cy2.toFixed(1)} ${nx.toFixed(1)} ${ny.toFixed(1)}`;
    x = nx;
    y = ny;
  }
  return d;
}

/** All tendril paths, precomputed once (deterministic). */
export const SMOKE_PATHS: string[] = SMOKE_TENDRILS.map(smokePath);

/**
 * A gentle rising trajectory for an ember spark (used with
 * <animateMotion>). Deterministic per seed.
 */
export function emberTrail(seed: number): string {
  const rnd = mulberry32(seed);
  const sway = 3 + rnd() * 4;
  const h = 16 + rnd() * 10;
  const mid = (rnd() - 0.5) * 6;
  return `M 0 0 C ${sway.toFixed(1)} ${(-h * 0.35).toFixed(1)} ${mid.toFixed(1)} ${(-h * 0.7).toFixed(1)} ${(mid + sway * 0.4).toFixed(1)} ${(-h).toFixed(1)}`;
}
